name: Process Design Tokens

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  process-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Process design tokens
      run: |
        npx style-dictionary build

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update design tokens" && git push) 

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
